# Generated by Django 4.1.3 on 2023-01-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0422_multiuseinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmuserdefault',
            name='enter_sends',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enter_sends',
            field=models.BooleanField(default=True),
        ),
    ]
