# Generated by Django 5.0.6 on 2024-08-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0423_alter_realmuserdefault_enter_sends_and_more'),
        ('zerver', '0558_realmuserdefault_web_animate_image_previews_and_more'),
    ]

    operations = [
    ]
